version: "3.9"

services:
  catalogdb:
    container_name: Catalogdb_name
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: CatalogDB
    restart: always
    ports:
      - "5432:5432"   # expose Postgres to host machine
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

volumes:
  postgres_catalog:
    driver: local